### PR TITLE
Add support for remote references and support for both single and double qoutes

### PR DESCRIPTION
**Pull request by gayanper**
This change will add completion from files that are referenced relative to the current working directory like
`$ref: 'org.gap.shared.spec.yaml#'` where pressing for auto completion will show definitions from org.gap.shared.spec.yaml file.

This change also support auto completion with both " and ' as well.

### CODE REVIEW

**Comment by ak1394** [comment]
Thanks for PR! I didn't notice it, so it was sitting there for a while... I'll merge it next week.

**Comment by gayanper** [comment]
No problem @ak1394

**Comment by gayanper** [comment]
@ak1394 when will this feature be released ?

**Comment by ak1394** [comment]
Ah, sorry missed your comment once again! It'll be included with the next release, though at the moment we're trying to decide if we should release 3.6 in the next few days or perhaps add some more features and call it 4.0 (but that'll delay the release by a few more weeks). I'll let you know once it's been decided.

**Comment by ak1394** [comment]
@gayanper your changes has been included in todays release

**Comment by gayanper** [comment]
Thanks @ak1394

**Pull request merged**
